### ISSUE TITLE
deploylambda build script fails if region is "us-east-1" and S3 bucket doesn't exist

### ISSUE THREAD

**Issue by moanany** [awslabs/amazon-rekognition-video-analyzer#1]
If the S3 bucket used as a deployment target does not exist, the `deploylambda` build script attempts to create it by calling the [create_bucket](https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.create_bucket)() Boto3 API specifying a `LocationConstraint` set to the region name of the current AWS CLI profile. 

Boto3 generates an `InvalidLocationConstraint` exception if the region specified as an argument is `us-east-1` (see https://github.com/boto/boto3/issues/125).

Issue originally reported by Jenil Shah as a comment on the blog post:

https://aws.amazon.com/blogs/ai/create-a-serverless-solution-for-video-frame-analysis-and-alerting/

**Comment by RooCoder** [comment]
I am still getting the below error while doing the deploylambda - 
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "<NO-DEFAULT>": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"

What am I supposed to update here

**Comment by moanany** [comment]
It seems like a bucket name parameter is set to an empty string in config/cfn-params.json. The parameters reference in the docs explains each parameter. Did you check there?
