### ISSUE TITLE
localhost:8080 page is static

### ISSUE THREAD

**Issue by jtlz2** [awslabs/amazon-rekognition-video-analyzer#12]
I completed all the build steps successfully on macOS 10.13.1.

webui is running:

[ build.pyc - Starting task "webuiserver" ]
Starting local Web UI Server in directory 'build/web-ui/' on port 8080
127.0.0.1 - - [14/Dec/2017 09:08:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:31] "GET /src/app.css HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:31] "GET /src/js/axios.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:31] "GET /src/js/vue.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:31] "GET /logo.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:31] "GET /src/apigw.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:31] "GET /src/app.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:32] "GET /favicon-16x16.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:32] "GET /favicon-32x32.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:32] "GET /favicon-96x96.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:42] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:08:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:10:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:10:59] "GET /src/apigw.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:07] "GET /src/app.css HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:07] "GET /src/js/axios.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:07] "GET /src/js/vue.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:07] "GET /logo.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:07] "GET /src/apigw.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:07] "GET /src/app.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:08] "GET /favicon-96x96.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:08] "GET /favicon-32x32.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:08] "GET /favicon-16x16.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2017 09:11:14] "GET / HTTP/1.1" 200 -

videocapture[20] is returning output.

But the http://localhost:8080 page is static and the dotted box contains no output.

What could be going wrong?

Thanks!

**Comment by moanany** [comment]
Hello,

Here are a two debugging steps:

1) Activate "Developer Tools" in Google Chrome or similar in Firefox, and check for any errors in response to HTTPS requests going out from the Web UI.
2) From the Lambda console, check the Lambda function CloudWatch logs. There might be a configuration parameter issue causing your Lambda functions to fail. Check the logs of both Frame Fetcher and Image Processor functions.

This will give us some clues about what's causing the ingested frames to not appear.

Hope that helps!

**Comment by jtlz2** [comment]
It's working - right down to the SMSs - and I am super impressed at how easily so!

The issue was I think with pytz not having made it into the stack (second pip install pytz command).

Huge thanks!

**Comment by moanany** [comment]
Fantastic, glad you got that issue sorted out!
