### ISSUE TITLE
ImportError: No module named cv2

### ISSUE THREAD

**Issue by karhtickvalentino** [awslabs/amazon-rekognition-video-analyzer#15]
Hi,
I followed all the steps when i run  pynt videocaptureip["<your-ip-cam-mjpeg-url>",<capture-rate>] , I get 
[ build.pyc - Starting task "videocaptureip" ]
Traceback (most recent call last):
  File "video_cap_ipcam.py", line 13, in <module>
    import cv2
ImportError: No module named cv2
[ build.pyc - Completed task "videocaptureip" ]
. can anyone help me.

**Comment by vikaschouhan** [comment]
opencv python module is not installed.

**Comment by karhtickvalentino** [comment]
Can you help me with the installation. I have downloaded and extracted it. But it still throws the error. Where should I extract it to. I am new to python.
