### ISSUE TITLE
Typo in the Readme: parameter RtRekogS3BucketNameParameter in cfn-params.json does not exist

### ISSUE THREAD

**Issue by shazic** [awslabs/amazon-rekognition-video-analyzer#5]
For parameter `s3_bucket` of **imageprocessor-params.json**, the instructions in the readme file say:

> The value specified here must match the value specified for the RtRekogS3BucketNameParameter parameter in the cfn-params.json file.

However, the parameter `RtRekogS3BucketNameParameter` is not defined in cfn-params.json.
This parameter is not used in any programs either.

This could be a typo, or is it the FrameS3BucketNameParameter that it is trying to refer to?

**Comment by moanany** [comment]
@shazic Thank you for pointing this out. I've just fixed it.
